providers:
  - url: 'wss://'
    config:
      priority: 2
      stallTimeout: 200
      weight: 2
  # ... continue with the list of providers. can be either http/ws

contracts:
  - name: "Name of the PAIR"
    # Number of block confirmations before tx must be sent
    blockConfirmations:
      # Source chain
      sourceChain:
      # Destination chain
      destinationChain:
    # Time to wait before sending another tx. Essentially would move this into something dynamic
    interval: 
    # Contract which has more weight than the other (source of truth)
    sourceContract:
      address: 
      pathToArtifact: 
      eventsToWatch:
        - "test"
    # Destination Contract
    destinationContract:
      address:
      pathToArtifact:
      eventsToWatch:
        - "test"
    # Limit of Ratio to be kept between contracts(percentage)
    healthRatio: 0.1
    
    
    