providers:
  sourceNetwork:
    - url: "wss://eth-mainnet.ws.alchemyapi.io/v2/oFT4VovUd2RoaXwFAjIPvD3i2aA2KQ6k"
      config:
        priority: 1
        stallTimeout: 200
        weight: 2
      networkId: 1
  targetNetwork:
    - url: "wss://data-seed-prebsc-1-s1.binance.org:8545"
      config:
        priority: 1
        stallTimeout: 200
        weight: 2
      networkId: 97

  # ... continue with the list of providers. can be either http/ws

contracts:
  - name: "TEST"
    # Number of block confirmations before tx must be sent
    blockConfirmations:
      # Source chain
      sourceChain: 6
      # Destination chain
      targetChain: 6
    # Time to wait before sending another tx. Essentially would move this into something dynamic
    interval: 300
    # Contract which has more weight than the other (source of truth)
    sourceContract:
      address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      pathToArtifact: "artifacts/TetherToken.json"
      eventsToWatch:
        - "Transfer"
    # Destination Contract
    targetContract:
      address: "0x26d80fFc9c0cB79EB91B606DD6A05654C88e2Ec8"
      pathToArtifact: "artifacts/BridgeTarget.json"
      eventsToWatch:
        - "DepositToken"
    # Limit of Ratio to be kept between contracts(percentage)
    healthRatio: 0.90
  - name: "TEST2"
    blockConfirmations:
      sourceChain: 6
      targetChain: 6
    interval: 300
    sourceContract:
      address: "0xd5faa4aBd587E627Afb8CE972E080fb4a08eBDd1"
      pathToArtifact: "artifacts/BridgeSource.json"
      eventsToWatch:
        - "DepositToken"
    targetContract:
      address: "0x26d80fFc9c0cB79EB91B606DD6A05654C88e2Ec8"
      pathToArtifact: "artifacts/BridgeTarget.json"
      eventsToWatch:
        - "DepositToken"
    healthRatio: 0.90
    
    
    