providers:
  sourceNetwork:
    - url: "wss://rinkeby.infura.io/ws/v3/c64ab21d647b491490edfb472386ba50"
      config:
        priority: 1
        stallTimeout: 200
        weight: 2
      networkId: 4
  sourceSignerEnv: "process.env.RINKEBY_SIGNER"
  targetNetwork:
    - url: "wss://data-seed-prebsc-1-s1.binance.org:8545"
      config:
        priority: 1
        stallTimeout: 200
        weight: 2
      networkId: 97
  targetSignerEnv: "process.env.BSC_SIGNER"

  # ... continue with the list of providers. can be either http/ws BUT specify the correct network ID!

contracts:
  - name: "TEST"
    # Number of block confirmations before tx must be sent
    blockConfirmations:
      # Source chain
      sourceChain: 6
      # Destination chain
      targetChain: 6
    # Time to wait before sending another tx. Essentially would move this into something dynamic
    interval: 300
    txLimit: 10
    # Contract which has more weight than the other (source of truth)
    sourceContract:
      address: "0x0c8f198D8D394B049f79BcA0A8FE530D884cE930"
      pathToArtifact: "artifacts/Bridge.json"
      eventsToWatch:
        - "DepositTokens"
    # Destination Contract
    targetContract:
      address: "0x0E0d98dE69341DdE6f8F6054f6a64aca516998e2"
      pathToArtifact: "artifacts/Bridge.json"
      eventsToWatch:
        -
    # Limit of Ratio to be kept between contracts(percentage)
    healthRatio: 0.90

  - name: "TEST2"
    blockConfirmations:
      sourceChain: 6
      targetChain: 6
    interval: 300
    sourceContract:
      address: "0xd5faa4aBd587E627Afb8CE972E080fb4a08eBDd1"
      pathToArtifact: "artifacts/Bridge.json"
      eventsToWatch:
        - "DepositTokens"
    targetContract:
      address: "0x26d80fFc9c0cB79EB91B606DD6A05654C88e2Ec8"
      pathToArtifact: "artifacts/Bridge.json"
      eventsToWatch:
        - "DepositTokens"
    healthRatio: 0.90
